# Stage 1: Build Angular App
FROM node:16 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --prod

# Stage 2: Serve Angular with Nginx
FROM nginx:stable-alpine
COPY ./nginx.config /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/zoom-clone/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
