version: '3.9'

services:
  # MongoDB Service
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_db:/data/db
  
  # Backend Service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8000:8000
    environment:
      DB_URI: mongodb://mongodb:27017/usersDb
      PORT: 8000
      APP_NAME: YOOM
    depends_on:
      - mongodb
    
  # Frontend Service
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 8080:80
    expose:
      - 80
    depends_on:
      - backend

volumes:
  mongo_db: {}
